import Link from 'next/link';
import { getChrome } from '@/server/sandbox/chrome';
import { listNotifications } from '@/server/sandbox/identity';
import { markNotificationsReadAction } from '@/server/sandbox/actions';
import type { NotificationView } from '@/lib/sandboxContract';
import { cn } from '@/lib/cn';
import { AppHeader } from '@/components/kit/AppChrome';
import { Icon, type IconName } from '@/components/kit/Icon';
import { Ago } from '@/components/kit/Time';
import { ToastProvider } from '@/components/kit/Feedback';
import { ActionButton } from '@/components/flows/ActionButton';
import { Card, EmptyState, Shell } from '@/components/kit/primitives';

export const dynamic = 'force-dynamic';

/**
 * Notifications.
 *
 * Every row here was generated by something that actually happened on a
 * deal, in the same transaction as the event it describes — so a
 * notification cannot exist for a state change that rolled back. There is no
 * marketing channel and no digest: if it is in this list, someone did
 * something to a deal you are in.
 *
 * Unread is a real column, not a client flag, so the count in the header and
 * the highlight here can never disagree.
 */
const SEVERITY: Readonly<
  Record<NotificationView['severity'], { icon: IconName; ring: string; tint: string }>
> = {
  ACTION: {
    icon: 'clock',
    ring: 'border-[var(--color-brand-line)]',
    tint: 'bg-[var(--color-brand-tint)] text-[var(--color-brand)]',
  },
  WARNING: {
    icon: 'alert',
    ring: 'border-[var(--color-risk-line)]',
    tint: 'bg-[var(--color-risk-tint)] text-[var(--color-risk)]',
  },
  INFO: {
    icon: 'info',
    ring: 'border-[var(--color-line)]',
    tint: 'bg-[var(--color-sunken)] text-[var(--color-ink-3)]',
  },
};

export default async function NotificationsPage() {
  const { user, unread } = await getChrome();
  const items = await listNotifications(user);

  return (
    <ToastProvider>
      <AppHeader
        title="Notifications"
        subtitle={unread > 0 ? `${unread} unread` : 'All caught up'}
        back={{ href: '/app', label: 'Back to home' }}
        bell={false}
        actions={
          unread > 0 ? (
            <ActionButton
              action={markNotificationsReadAction}
              success="Marked all as read"
              icon="check"
              size="sm"
            >
              <span className="hidden sm:inline">Mark all read</span>
              <span className="sm:hidden">Read</span>
            </ActionButton>
          ) : null
        }
      />

      <Shell width="prose" className="py-5 sm:py-7">
        {items.length === 0 ? (
          <EmptyState
            icon="bell"
            title="Nothing yet"
            body="When someone joins one of your deals, marks a payment, or reports a problem, it appears here."
            action={{ href: '/app/new', label: 'Create a protected deal' }}
          />
        ) : (
          <ul className="space-y-2.5">
            {items.map((item) => {
              const meta = SEVERITY[item.severity];
              const body = (
                <>
                  <span
                    className={cn(
                      'grid h-9 w-9 shrink-0 place-items-center rounded-full',
                      meta.tint,
                    )}
                  >
                    <Icon name={meta.icon} className="h-4 w-4" />
                  </span>
                  <span className="min-w-0 flex-1">
                    <span className="flex items-start justify-between gap-3">
                      <span
                        className={cn(
                          'text-[length:var(--text-base)] text-[var(--color-ink)]',
                          item.read ? 'font-medium' : 'font-semibold',
                        )}
                      >
                        {item.title}
                      </span>
                      {!item.read ? (
                        <span
                          aria-label="Unread"
                          className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-[var(--color-brand)]"
                        />
                      ) : null}
                    </span>
                    <span className="mt-0.5 block text-[length:var(--text-sm)] leading-relaxed text-[var(--color-ink-2)]">
                      {item.body}
                    </span>
                    <span className="mt-1 block text-[length:var(--text-2xs)] text-[var(--color-ink-4)]">
                      <Ago iso={item.createdAt} />
                    </span>
                  </span>
                </>
              );

              const shape = cn(
                'flex items-start gap-3 rounded-[var(--radius-lg)] border bg-[var(--color-paper)] p-3.5 shadow-[var(--shadow-card)]',
                item.read ? 'border-[var(--color-line)]' : meta.ring,
              );

              return (
                <li key={item.notificationId}>
                  {item.dealId ? (
                    <Link
                      href={`/app/deal/${item.dealId}`}
                      prefetch={false}
                      className={cn(shape, 'press hover:bg-[var(--color-sunken)]')}
                    >
                      {body}
                    </Link>
                  ) : (
                    <div className={shape}>{body}</div>
                  )}
                </li>
              );
            })}
          </ul>
        )}

        {items.length > 0 ? (
          <Card tone="sunken" className="mt-5">
            <p className="text-[length:var(--text-xs)] leading-relaxed text-[var(--color-ink-3)]">
              Each of these was written in the same transaction as the event it describes, so a
              notification cannot exist for a change that was rolled back. Nothing here is
              marketing.
            </p>
          </Card>
        ) : null}
      </Shell>
    </ToastProvider>
  );
}
